default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DB_HOST') { 'db' } %>

development:
  <<: *default
  database: rails_grapql_sample_development
  password: <%= ENV.fetch('DB_PASSWORD') { 'postgres' } %>

test:
  <<: *default
  database: rails_graphql_sample_test
  username: postgres
  password: <%= ENV.fetch('DB_PASSWORD') { 'postgres' } %>

production:
  <<: *default
  database: rails_graphql_sample_production
  username: rails_graphql_sample
  password: <%= ENV['RAILS_GRAPHQL_SAMPLE_DATABASE_PASSWORD'] %>
